name: Initialize images
on:
  workflow_dispatch:

jobs:
  generate-content:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: write
      packages: write
      id-token: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: yarn install

      - name: Initialize images
        run: yarn initialize-images

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "📝 Initialize images" --no-verify && git push)
